<?php
namespace MirrorApiBundle\Repository;
use MirrorApiBundle\Entity\User;
use \Doctrine\ORM;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
}
