# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
    auth_token_user_provider:
        class: MirrorApiBundle\Security\AuthTokenUserProvider
        arguments: ["@auth_token_repository", "@user_repository"]
        public:    false

    auth_token_repository:
        class:   Doctrine\ORM\EntityManager
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments: ["MirrorApiBundle:AuthToken"]

    user_repository:
        class:   Doctrine\ORM\EntityManager
        factory: ["@doctrine.orm.entity_manager", "getRepository"]
        arguments: ["MirrorApiBundle:User"]

    auth_token_authenticator:
        class:     MirrorApiBundle\Security\AuthTokenAuthenticator
        arguments: ["@security.http_utils"]
        public:    false

    security.access.owner_voter:
        class:      MirrorApiBundle\Security\Authorization\Voter\OwnerVoter
        public:     false
        tags:
            - { name: security.voter }