MirrorApiBundle\Entity\Weather:
    exclusion_policy: none
    accessor_order: custom
    custom_accessor_order: [id, type, name, position, city, country, user]
    properties:
        id:
            groups: ['user', 'module']
        type:
            groups: ['user', 'module']
        name:
            groups: ['user', 'module']
        position:
            groups: ['user', 'module']
        city:
            groups: ['user', 'module']
        country:
            groups: ['user', 'module']
        user:
            groups: ['module']