MirrorApiBundle\Entity\User:
    exclusion_policy: none
    accessor_order: custom
    custom_accessor_order: [id, firstName, lastName, email, photoName, roles]
    properties:
        id:
            groups: ['user', 'module', 'auth-token', 'users']
        firstName:
            groups: ['user', 'module', 'auth-token', 'users']
        lastName:
            groups: ['user', 'module', 'auth-token', 'users']
        photoName:
            groups: ['user', 'module', 'auth-token', 'users']
        email:
            groups: ['user', 'module', 'auth-token', 'users']
        password:
            exclude: true
        plainPassword:
            exclude: true
        modules:
            groups: ['user']
    virtual_properties:
        expression_prop:
            exp: object.getRoles()
            serialized_name: roles
            type: array
            groups: ['users']